---
# the present playbook is based on the official docker doc: https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository
- name: Install Docker on Ubuntu 24.04
  hosts: wheecious01
  become: yes

  tasks:
    - name: remove repos sources # I had it previously installed with another script
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/apt/sources.list.d/docker.list
        - /etc/apt/sources.list.d/docker-ce.list

    - name: packages from the doc
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: add docker off gpg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add repo
      apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu noble stable"
        state: present
        filename: docker

    - name: install
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: ensure service
      service:
        name: docker
        state: started
        enabled: yes

    - name: add user to the docker group
      user:
        name: "{{ docker_user }}"
        groups: docker
        append: yes
