global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'filebeat'
    static_configs:
      - targets: ['filebeat:5066']
        labels:
          instance: "filebeat"

  - job_name: 'json_filebeat'
    metrics_path: /probe
    params:
      module: [filebeat]
      target: ['http://filebeat:5066/stats']
    static_configs:
      - targets: ['json_exporter:7979']
        labels:
          instance: "filebeat"
